### ISSUE TITLE
DICOM Tag Error

### ISSUE THREAD

**Issue by ebaad** [vivek8981/DICOM-to-JPG#1]
When extracting DICOM tags, I get the following error, any help would be appreciated.

```
c:\python>python c:\scripts\extdcm.py
Traceback (most recent call last):
  File "c:\scripts\extdcm.py", line 21, in <module>
    if ds.data_element(field) is None:
  File "c:\python\lib\site-packages\pydicom\dataset.py", line 450, in data_element
    return self[tag]
  File "c:\python\lib\site-packages\pydicom\dataset.py", line 847, in __getitem__
    data_elem = self._dict[tag]
KeyError: (0018, 0015)
```

**Comment by Shivaraj1995** [comment]
with open('Patient_Detail.csv', 'w', newline ='') as csvfile:
    fieldnames = list(dicom_image_description["Description"])
    writer = csv.writer(csvfile, delimiter=',')
    writer.writerow(fieldnames)
    for n, image in enumerate(images_path):
        ds = dicom.dcmread(os.path.join(folder_path, image))
        rows = []
        pixel_array_numpy = ds.pixel_array
        if PNG == False:
            image = image.replace('.dcm', '.jpg')
        else:
            image = image.replace('.dcm', '.png')
        cv2.imwrite(os.path.join(jpg_folder_path, image), pixel_array_numpy)
        if n % 50 == 0:
            print('{} image converted'.format(n))
        for field in fieldnames:
            if ds.get(field,None) is None:
                rows.append('')
            else:
                x = str(ds.get(field)).replace("'", "")
                y = x.find(":")
                x = x[y+2:]
                rows.append(x)
        writer.writerow(rows)

**Comment by clearc352** [comment]
use "try" to ignore KeyError
(because you image mis some information? )
